### PR TITLE
adding new template markdown_split

### PR DESCRIPTION
**Pull request by michaelwhitford**
I added a markdown_split template that can be used for easy import to a [gollum wiki](https://github.com/gollum/gollum/wiki).

### CODE REVIEW

**Comment by fboender** [comment]
Hey, nice job!

When I generate the markdown files and open the "overview.md" file, and click on one of the links, it links to the wrong file. It looks like the ".md" extension is missing from the links. Is this intentional behavior because you're importing it into a wiki?

**Comment by michaelwhitford** [comment]
Yes, I am using this to import to gollum, which is a wiki that runs out of a git repo.  I will fix the links so they are properly linked outside the wiki, since gollum adds the .md automagically.  I should be able to update this tonight.

**Comment by fboender** [comment]
Awesome! That'll mean other people can also just use it as plain markdown with correct links. Thank for taking the time to fix this!

**Comment by michaelwhitford** [comment]
Not sure how I got extra commits, but the output is now correct.  I am a beginner with git.

**Comment by fboender** [comment]
Looks good! I've merged it. Thanks for your work!

**Pull request merged**
