### PR TITLE
Add arch linux to system package list

### PR DESCRIPTION
**Pull request by gregf**

### CODE REVIEW

**Comment by fboender** [comment]
Cool, thanks!

**Comment by fboender** [comment]
https://aur.archlinux.org/packages/ansible-cmdb/ lists the license for ansible-cmdb as MIT, but the license is actually GPLv3. Or is that the license for the packaging work (PKGBUILD)?

**Comment by gregf** [comment]
My mistake, I'll fix the license in just a minute. Thanks for merging this.

**Comment by fboender** [comment]
Thank you for taking the time to create an AUR!

**Pull request merged**
