### PR TITLE
fancy_html is much more impressive when the js/css loads

### PR DESCRIPTION
**Pull request by MTN-RowinAndruscavage**

### CODE REVIEW

**Comment by muffl0n** [comment]
Do the proocol-relative links don't work if you access the generated file via file://?
Never even thought about that. :)

I would prefer the links to be https though.

**Comment by fboender** [comment]
Hi Rowan!

Thanks for the pull request. The thing is, those URLs are (as muffl0n said) protocol-relative links. More infromation about them is here: https://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/

The idea is that they work whether you serve the generated page over both HTTP and HTTPS. The downside is that they don't work when you access the page via `file:///` links. We could do what your PR does and hardcode in either http or https, but that'll stop the resources from working on certain browsers (chrome) if the page is served over the other protocol. 

There are two solutions to this problem:

You can serve the page over a HTTP server. Python has a built-in one that'll do just that:

    $ ansible-cmdb out/ > overview.html
    $ python -m SimpleHTTPServer
    Serving HTTP on 0.0.0.0 port 8000 ...

You can now access the file with the http://127.0.0.1:8000/overview.html URL. The other option (which isn't included in packages releases yet!) is to supply the `-p local_js=1` commandline parameter to make ansible-cmdb generate file:/// links in the output page. This'll require the javascript files to be present in `/usr/lib/ansible-cmdb/static/js/`. These files will be automatically installed from version 1.4 of ansible-cmdb.

Hope that helps!

Regards,

Ferry

**Comment by fboender** [comment]
I've just released v1.4 of ansible-cmdb, which includes the `-p local_js=1` option. You can find the downloads at https://github.com/fboender/ansible-cmdb/releases

**Comment by muffl0n** [comment]
``...hardcode in either http or https, but that'll stop the resources from working on certain browsers (chrome) if the page is served over the other protocol.``
Could you elaborate on this? When we hardcode https it works whether you access the page via file://, http:// or https://

I totally see that accessing the generated page via file:// is a useful use case.

**Comment by fboender** [comment]
If we hardcode the HTTP protocol in the URLS, you won't be able to view the page over HTTPS anymore:

    Mixed Content: The page at 'https://electricmonk.nl/cmdb.html' was loaded over 
    HTTPS, but requested an insecure stylesheet 
    'http://cdn.datatables.net/1.10.5/css/jquery.dataTables.css'. This request has been
    blocked; the content must be served over HTTPS.

I've just tested if we can hardcode the HTTPS protocol, and that seems to work in at least Chrome and Firefox for http://, https:// and file:// access. I'm going to go ahead and commit that change.

**Comment by muffl0n** [comment]
That's what I meant. :)

**Comment by fboender** [comment]
Yeah, I saw you mentioned https after I had already commented :) I think I need glasses ;-)

**Comment by MTN-RowinAndruscavage** [comment]
Oh, cool, you're 2 steps ahead of me!   local_js is exactly what I need for now :D

**Pull request closed without merging**
