### PR TITLE
fancy_html template tweaks

### PR DESCRIPTION
**Pull request by MTN-RowinAndruscavage**
Add some useful columns and improve sorting

### CODE REVIEW

**Comment by fboender** [comment]
Hey Rowin!

Thanks for the pull request. It looks like some old commits also got included. You probably worked on this branch before, I guess.

There were a few too many changes per commit (and too many commits per merge request), so I've merged some of your changes manually. I've added the additional columns for the kernel and the timestamp you added. I'll have to take a look at the memory column changes. They seem useful, but I don't want to remove the old-style memory column. I haven't merged the changes that turn of some of the  current columns, as I want them in the output.

Thanks!

**Comment by fboender** [comment]
I've added a --columns / -c option to ansible-cmdb. You can use it to specify which columns you'd like to see in the output from the command-line.

**Comment by MTN-RowinAndruscavage** [comment]
Cool, thanks!   I wasn't expecting all the things to get accepted, but thought it was worth a shot to see what you'd find useful!

The old memory column is still there and just renamed "RAM [GB]", but removed the "g" from the end so it sorts properly.  I liked what you had with the disk bar graphs, so just used that for the new "memory usage" and "swap usage" columns, which I find useful for resource rebalancing.

**Comment by fboender** [comment]
I'm going to merge some more stuff from your merge request now that I've implemented the --columns switch. I didn't find the memory usage column very useful for myself, since it changes way too much. But now that it can be turned on for those who do want it, I might as well add it. 

Removing the 'g' from the memory column also seems like a good idea.

Thanks for the contributions! I've referred to your contributions in the CHANGELOG.

**Comment by MTN-RowinAndruscavage** [comment]
Hey, sorry for leaving in the old commits, should have started with a clean git checkout ;-)  Let me just talk through some of the other things that were buried in that PR.  If you find any of these interesting let me know and I'll clean up my git branch and do a new PR with individual commits for each feature, so you can cherry pick the ones you want.... would rather have you working on core cmdb functionality than fussing around with templates ^_^

* "Mem"  column renamed to "RAM [GB]" and conversion from MB corrected from  /1000 to /1024  (actually, I should probably use "[GiB]" to be clear)

+ "CPU Type" column with last element from the ansible_processor list (usually something like "Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz"

* "CPUs" column changed to "vCPUs"  and uses the ansible_processor_vcpus  instead of ansible_processor_count (which on physical boxes seems to only provide physical socket count and not total CPU cores count).  vcpus still isn't ideal because it also counts HyperThreading as extra cores, but it's still better than characterizing our "Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz" as having "1" processor versus "12" (6 cores x2 for HT) 

+ "Memory usage" and "Swap usage" columns : yes, these really belong more in a systems monitoring tool like Icinga2, but ansible_facts provides good values for mem usage (that don't include cache+buffers which are essentially "free") so it'd be nice to have a sortable bar graph of them.  Plus, I often find this information critical in a CMDB for resource planning.  Use case:  managers are always asking "where can we save money in our cloud by decreasing the number of vCPU/RAM in our instances".   So having this info in the CMDB really helps us go back to them with "well, this app pool is using only 5% of their huge instances, while this other app pool is choking on their peasley little 2GB VMs"

* "Disk usage": added the "hidden sort helper" which puts the percentage fraction ( in the form: 0.000 - 1.000 ) in front of the cell contents so the JQuery properly sorts it by usage percentage, instead of alphabetically on the string e.g. "(6.87g / 8.06g)"  which doesn't always come out right.   This still isn't ideal, since it'll only sort by the usage of the first "/" partition, but it's an improvement.   In the future we could run an additional loop through all the mount points and use the max % utilized as the "hidden sort helper", but that'll take some more explaining.

* update example/html_fancy.html to reflect changes in template.  FWIW, if you haven't already, you can play with what the output above looks like with
```
wget https://raw.githubusercontent.com/mtnsat/ansible-cmdb/fancy_html/example/html_fancy.html
open html_fancy.html
```

**Comment by fboender** [comment]
> Hey, sorry for leaving in the old commits, should have started with a
clean git checkout ;-)

No worries! I'm a bit too pendantic about clean commits. It makes it easier
to see what's been changed. :-) I always feel a bit guilty not merging the
actual pull requests even if the changes are useful. People go through all
that trouble and then don't get the satisfaction of getting their pull
requests merged!

The whole list looks awesome, and I'd love to get separate pull requests
for all those features actually. For the memory usage column, I'd like to
keep the old memory column in as well, if you could.

Regards,

Ferry

**Comment by MTN-RowinAndruscavage** [comment]
Re-doing this in new PRs
https://github.com/fboender/ansible-cmdb/pull/42

**Pull request closed without merging**
